core/urls.py
from django.urls import path
from .views import LoginHomeView, HomePageView, SignOutView


urlpatterns = [
    path('', LoginHomeView.as_view(), name='login_home'),
    path('inicio/', HomePageView.as_view(), name='home'),
    path('logout/', SignOutView.as_view(), name='logout'),
]

usuarios/urls.py
from django.urls import path
from .views import DatosPersonelesUpdate, DatosPersonalesCreateView

urlpatterns = [
    path('create/', DatosPersonalesCreateView.as_view(), name='create_datospersonales'),
    path('update/', DatosPersonelesUpdate.as_view(), name='update_datospersonales'),
]

veggiex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('user/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

cultivo/models.py
from django.db import models
from django.utils.timezone import now
from usuarios.models import DatosPersonales

# Create your models here.
class Sensor(models.Model):
    latidude = models.FloatField( blank=True, null=True, verbose_name='Latitude')
    longitude = models.FloatField(blank=True, null=True, verbose_name='Longitude')
    imei = models.CharField(max_length=15, primary_key=True, verbose_name='IMEI')
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Sensor"
        verbose_name_plural = "Sensores"

    def __str__(self):
        return "{}".format(self.imei)


class DataSensor(models.Model):
    sensor = models.ForeignKey(Sensor, verbose_name="Sensor", on_delete=models.CASCADE)
    humedad_ambiental = models.FloatField(verbose_name="Humedad ambiental")
    temperatura_ambiental = models.FloatField(verbose_name="Temperatura ambiental")
    suelo_uno_hum = models.FloatField(verbose_name="Suelo uno Humedad")
    suelo_uno_tem = models.FloatField(verbose_name="Suelo uno temperatura")
    suelo_uno_con = models.FloatField(verbose_name="Suelo uno conductividad")
    suelo_dos_hum = models.FloatField(verbose_name="Suelo dos humedad")
    suelo_dos_tem = models.FloatField(verbose_name="Suelo dos temperatura")
    suelo_dos_con = models.FloatField(verbose_name="Suelo dos conductividad")
    hoja_hum = models.FloatField(verbose_name="Hoja Humedad")
    hoja_temp = models.FloatField(verbose_name="Hoja temperatura")
    luminosidad = models.FloatField(verbose_name="Luminosidad")
    velocidad_viento = models.FloatField(verbose_name="Velocidad del viento")
    direccion_viento = models.CharField(max_length=10, verbose_name="Direccion del viento")
    radiacion_solar = models.FloatField(verbose_name="Radiacion solar")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")


    class Meta:
        verbose_name = "Data Sensor"
        verbose_name_plural = "Data Sensores"

    def __str__(self):
        return "{}".format(self.sensor)



class Cultivo(models.Model):
    nombre = models.CharField(max_length=200, verbose_name="Nombre del cultivo")
    descripcion = models.TextField(verbose_name="Descripcion")
    siembra_published = models.DateTimeField(verbose_name="Fecha de siembra", default=now)
    sensor = models.ForeignKey(Sensor, verbose_name="Sensor", on_delete=models.CASCADE)
    propietario = models.OneToOneField(DatosPersonales, verbose_name="Propietario", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")


    class Meta:
        verbose_name = "Cultivo"
        verbose_name_plural = "Cultivos"

    def __str__(self):
        return "{}".format(self.nombre)

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class DatosPersonales(models.Model):
    primer_nombre = models.CharField(max_length=100, verbose_name="Primer nombre")
    segundo_nombre = models.CharField(max_length=100, verbose_name="Segundo nombre", blank=True, null=True)
    apellido_paterno = models.CharField(max_length=200, verbose_name="Apellido paterno")
    apellido_materno = models.CharField(max_length=200, verbose_name="Apellido materno", blank=True, null=True)
    email = models.EmailField(max_length=200, verbose_name="Email", blank=True, null=True)
    telefono = models.CharField(max_length=10, verbose_name="Telefono")
    usuario = models.OneToOneField(User, verbose_name="Usuario", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")

    class Meta:
        verbose_name = "datos personales"
        verbose_name_plural = "datos personales"
        ordering = ['-created']

    def __str__(self):
        return "{} {}".format(self.primer_nombre, self.apellido_paterno)

usuarios/forms.py
from django import forms
from .models import DatosPersonales


class DatosPersonalesForm(forms.ModelForm):
    class Meta:
        model = DatosPersonales
        fields = ['primer_nombre', 'segundo_nombre',
                  'apellido_paterno', 'apellido_materno', 'email', 'telefono']

core/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from .mixins import CoreAuthMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from cultivo.models import Cultivo, Sensor, DataSensor
from usuarios.models import DatosPersonales
# Create your views here.


class LoginHomeView(LoginView):
    """Login y presentacion"""
    template_name = "core/home.html"


class HomePageView(CoreAuthMixin, ListView):
    """Inicio"""
    template_name = "core/data.html"
    model = Cultivo
    
    def get_queryset(self):
        usuario = self.request.user
        if DatosPersonales.objects.filter(usuario=usuario):
            datospersonales = DatosPersonales.objects.get(usuario=usuario)
            return Cultivo.objects.filter(propietario=datospersonales)
    
    def get_context_data(self, **kwargs):
        datasensor = super().get_context_data(**kwargs)
        usuario = self.request.user
        propietario = DatosPersonales.objects.get(usuario=usuario)
        if Cultivo.objects.filter(propietario=propietario):
            print('si hay cultivo')
            cultivo = Cultivo.objects.get(propietario=propietario)
            sensor = Sensor.objects.get(imei=cultivo.sensor)
            if DataSensor.objects.filter(sensor=sensor):
                print('si hay sensor data')
                #senosrdata = DataSensor.objects.get(sensor=sensor)
                senosrdata = DataSensor.objects.filter(sensor=sensor).reverse()[0]
                datasensor['data_sensor'] = senosrdata
                return datasensor
            else:
                print('no hay sensor data')
                pass
        else:
            print('no hay cultivo')
            pass
        #return datasensor

    def dispatch(self, request, *args, **kwargs):
        usuario = self.request.user
        if DatosPersonales.objects.filter(usuario=usuario).exists():
            return super(HomePageView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('create_datospersonales')
    

class SignOutView(LogoutView):
    """Cerrar secion"""
    pass

cultivo/views.py
from django.shortcuts import render

# Create your views here.

usuarios/views.py
from django.shortcuts import render
from django.views.generic.edit import UpdateView, CreateView
from django.urls import reverse_lazy
from .forms import DatosPersonalesForm
from .models import DatosPersonales
# Create your views here.


class DatosPersonelesUpdate(UpdateView):
    form_class = DatosPersonalesForm
    success_url = reverse_lazy('home')
    template_name = 'usuarios/datospersonales_form.html'

    def get_object(self):
        datospersonales, create = DatosPersonales.objects.get_or_create(usuario=self.request.user)
        return datospersonales

#sin formulario
class DatosPersonalesCreateView(CreateView):
     form_class = DatosPersonalesForm
     #model = DatosPersonales
     #fields = ['primer_nombre', 'segundo_nombre','apellido_paterno', 'apellido_materno', 'email', 'telefono']
     success_url = reverse_lazy('home')
     template_name = 'usuarios/datospersonales_form.html'

     def form_valid(self, form):
          form.instance.usuario = self.request.user
          return super(DatosPersonalesCreateView, self).form_valid(form)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Fuentes -->
    <link href="{% static 'core/css/normalize.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/materialize.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/style.css' %}" rel="stylesheet">
    
</head>
<body>
    <!-- Contenido -->
    {% block content %}{% endblock %}
    <!-- Javascript -->
    <script src="{% static 'core/js/jquery.min.js' %}"></script>
    <script src="{% static 'core/js/materialize.min.js' %}"></script>
    {% block script_block %}{% endblock %}
</body>
</html>

core/templates/core/clima.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Clima{% endblock %}
{% block content %}
<div class="container">
    <h1 id='clima'></h1>
    <h2 id='lugar'></h2>
    <img id="img_clima" src="">
    <button onclick="getLocation()">Get my location.</button>
    <script>
    function getLocation() {
        var openWeatherMap = 'http://api.openweathermap.org/data/2.5/weather'
        if (window.navigator && window.navigator.geolocation) {
            window.navigator.geolocation.getCurrentPosition(function(position){
                $.getJSON(openWeatherMap, {
                    lat: position.coords.latitude,
                    lon: position.coords.longitude,
                    units: 'metric',
                    APPID: '3366e803629bef2ef00cbc0982d79a1c'
                }).done(function(data) {
                    //document.getElementById("clima").innerHTML = data.main.temp
                    //document.getElementById("lugar").innerHTML = data.name
                    $('#clima').text(data.main.temp)
                    $('#lugar').text(data.name)
                    let url_imagen = 'http://openweathermap.org/img/w/' +  data.weather[0].icon + '.png'
                    $('#img_clima').attr('src', url_imagen)
                    console.log(data)
                })
            })
        }
    } 
   </script>
</div>
{% endblock %}

core/templates/core/data.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
    <div class="">
        {% include 'core/includes/core_menu.html' %}
        <section class="row">
            <p>
                <h2>Bienvenido<b>Humedad: {{data_sensor.humedad_ambiental}}</b></h2>
            </p>
        {% if cultivo_list %}
            <h1>Cultivos creados</h1>
        {% else %}
            <h2>No hay cultivos creados</h2>
        {% endif %}
        <!-- {{cultivo_list}} -->
        <article class="col s9 m9 margen-login">
            <div class="row">
                {% for cultivo in cultivo_list %}
                <div class="col s12 m4">
                    <div class="card">
                        <div class="card-image">
                            <img style="height: 105px;" src="{% static 'core/img/lechuga.jpg' %}">
                        </div>
                        <div class="card-content">
                                <span class="card-title">{{cultivo.nombre}}</span>
                            <p><b>{{cultivo.sensor.latidude}}</b> Latitude</p><br>
                            <p>Alerta nivel de luminisidad altos</p>
                        </div>
                        <div class="card-action yellow darken-1">
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </article>
    </section>
    
    </div>
{% endblock %}

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
    <div class="fondo">
        
        <div class="row">
            <div class="col s12 m6 margen-logo">
                <div class="row">
                    <div class="col m1"></div>
                    <div class="col m3 logo">
                        <img class="logo" src="{% static 'core/img/hoja.jpg' %}">
                    </div>
                    <div class="col m1"></div>
                    <div class="col m5">
                        <span class="white-text"><p>
                            <h3>Veggiex</h3>
                            by Proinndev
                        </p></span>
                    </div>
                </div>
            </div>
            <div class="col s12 m4 margen-login">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title teal-text text-darken-2"><b>Accede a Veggiex</b></span>
                        <form action="" method="POST">{% csrf_token %}
                            <div class="row">
                                <div class="col s12">
                                    {% if form.non_field_errors %}
                                    <p style="color:red">Usuario o contraseña incorrectos, prueba de nuevo.</p>
                                    {% endif %}
                                </div>
                                <div class="input-field col s12">
                                    <input placeholder="admin" id="id_username" type="text" name="username" class="validate" required>
                                    <label for="id_username">Usuario</label>
                                </div>
                                <div class="input-field col s12">
                                    <input id="id_password" type="password" name="password"  class="validate" required>
                                    <label for="id_password">Password</label>
                                </div>
                            </div>
                            <input type="submit" class="waves-effect waves-light btn"" value=" Acceder">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/includes/core_menu.html
<ul id="dropdown1" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="{% url 'update_datospersonales' %}">actualizar datos</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'logout' %}">Salir</a></li>
</ul>
<nav class="cyan darken-4">
    <div class="nav-wrapper">
        <ul class="right">
            <!-- Dropdown Trigger -->
            <li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{request.user}}<i
                        class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
    </div>
</nav>

usuarios/templates/usuarios/datospersonales_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear Usuario{% endblock %}
{% block content %}
    <div>
        {% include 'core/includes/core_menu.html' %}
        <div class="row">
            <form class="col s12" action="" method="post">{% csrf_token %}
                <h4>Nombre:</h4>
                <div class="row">
                    <div class="input-field col s4">
                        {{form.primer_nombre}}
                        <label for="id_primer_nombre">Primer nombre</label>
                    </div>
                    {{form.primer_nombre.errors}}
                    <div class="input-field col s4">
                        {{form.segundo_nombre}}
                        <label for="id_segundo_nombre">Segundo nombre</label>
                    </div>
                </div>
                <h4>Apellidos:</h4>
                <div class="row">
                    <div class="input-field col s4">
                        {{form.apellido_paterno}}
                        <label for="id_apellido_paterno">Apellido paterno</label>
                    </div>
                    {{form.apellido_paterno.errors}}
                    <div class="input-field col s4">
                        {{form.apellido_materno}}
                        <label for="id_apellido_materno">Apellido materno</label>
                    </div>
                </div>
                <h4>Datos personales:</h4>
                <div class="row">
                    <div class="input-field col s4">
                        {{form.email}}
                        <label for="id_email">Email</label>
                    </div>
                    {{form.email.errors}}
                </div>
                <div class="row">
                    <div class="input-field col s4">
                        {{form.telefono}}
                        <label for="id_telefono">Telefono</label>
                    </div>
                    {{form.telefono.errors}}
                </div>
                <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
    </div>

{% endblock %}
{% block script_block %}
<script>
    $(document).ready(function () {
            Materialize.updateTextFields();
    });
</script>
{% endblock %}

usuarios/templates/usuarios/datospersonales_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear Usuario{% endblock %}
{% block content %}
<div>
    {% include 'core/includes/core_menu.html' %}
    <div class="row">
        <h1>Update datos personales</h1>
        <form class="col s12" action="" method="post">{% csrf_token %}
            <h4>Nombre:</h4>
            <div class="row">
                <div class="input-field col s4">
                    {{form.primer_nombre}}
                    <label for="id_primer_nombre">Primer nombre</label>
                </div>
                {{form.primer_nombre.errors}}
                <div class="input-field col s4">
                    {{form.segundo_nombre}}
                    <label for="id_segundo_nombre">Segundo nombre</label>
                </div>
            </div>
            <h4>Apellidos:</h4>
            <div class="row">
                <div class="input-field col s4">
                    {{form.apellido_paterno}}
                    <label for="id_apellido_paterno">Apellido paterno</label>
                </div>
                {{form.apellido_paterno.errors}}
                <div class="input-field col s4">
                    {{form.apellido_materno}}
                    <label for="id_apellido_materno">Apellido materno</label>
                </div>
            </div>
            <h4>Datos personales:</h4>
            <div class="row">
                <div class="input-field col s4">
                    {{form.email}}
                    <label for="id_email">Email</label>
                </div>
                {{form.email.errors}}
            </div>
            <div class="row">
                <div class="input-field col s4">
                    {{form.telefono}}
                    <label for="id_telefono">Telefono</label>
                </div>
                {{form.telefono.errors}}
            </div>
            <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>

{% endblock %}
{% block script_block %}
<script>
    $(document).ready(function () {
        Materialize.updateTextFields();
    });
</script>
{% endblock %}